/**
 * Copies the brand pieces the app shares with the website, so both always draw
 * the same logo and the same card-network marks.
 *
 *   ../src/components/ui/wordmark.ts   -> src/ui/generated/wordmark.ts
 *   ../src/assets/networks/*.svg       -> src/ui/generated/network-marks.ts (raw SVG strings, unmodified)
 *
 * Run after `npm run brand` in the website: npm run sync
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const OUT = "src/ui/generated";
mkdirSync(OUT, { recursive: true });

writeFileSync(`${OUT}/wordmark.ts`, readFileSync("../src/components/ui/wordmark.ts", "utf8"));

const marks = ["visa", "mastercard", "discover"].map((n) => {
  const svg = readFileSync(`../src/assets/networks/${n}.svg`, "utf8");
  return `export const ${n.toUpperCase()}_SVG = ${JSON.stringify(svg)};`;
});
writeFileSync(
  `${OUT}/network-marks.ts`,
  `// Card network marks, byte-for-byte copies of src/assets/networks/*.svg in the
// website (sources listed in src/dashboard/ui/BankCard.tsx there).
// Generated by scripts/sync-shared.mjs. Do not edit by hand.
${marks.join("\n")}
`,
);
console.log("synced wordmark and network marks into", OUT);
