import {
  BadgeCheck,
  Banknote,
  ChartPie,
  ChevronDown,
  Code,
  Coins,
  EyeOff,
  FileCheck,
  FileText,
  Fingerprint,
  Gauge,
  Github,
  KeyRound,
  Layers,
  Lock,
  Menu,
  Newspaper,
  Palette,
  Pause,
  Play,
  RadioTower,
  Receipt,
  Route,
  Server,
  ShieldCheck,
  Store,
  Terminal,
  WandSparkles,
  X as XIcon,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "badge-check": BadgeCheck,
  banknote: Banknote,
  "chart-pie": ChartPie,
  "chevron-down": ChevronDown,
  code: Code,
  coins: Coins,
  "eye-off": EyeOff,
  "file-check": FileCheck,
  "file-text": FileText,
  fingerprint: Fingerprint,
  gauge: Gauge,
  github: Github,
  "key-round": KeyRound,
  layers: Layers,
  lock: Lock,
  menu: Menu,
  newspaper: Newspaper,
  palette: Palette,
  pause: Pause,
  play: Play,
  "radio-tower": RadioTower,
  receipt: Receipt,
  route: Route,
  server: Server,
  "shield-check": ShieldCheck,
  store: Store,
  terminal: Terminal,
  "wand-sparkles": WandSparkles,
  x: XIcon,
};

export function Icon({ name, size = 24 }: { name: string; size?: number }) {
  const Cmp = MAP[name] ?? ShieldCheck;
  return <Cmp size={size} strokeWidth={2} aria-hidden="true" />;
}
